const proyectos = [
  {
    titulo: "CRM - Dev",
    descripcion:"Proyecto realizado usando el patrón de arquitectura MVC con PHP 8.3 junto con la base de datos MySQL. Cuenta con rutas protegitas, passwords hasheados, uso de sesiones asi como el manejo de usuario. Se implemento la libreria FullCalendar, Fetch API, el uso de Modulos en Javascript. Finalmente se usa el framework de css llamado Tailwind CSS. La cuenta de demo es: omar@correo y omar123.",
    tecnologias: ["php", "tailwind-css", "javascript"],
    tipo: "Fullstack",
    fecha: "13 Agosto 2024",
    enlace: "http://devomar-crmdev.x10.mx/",
    repositorio: "https://github.com/Dev-socar/CRM-Dev",
    imagen: "src/portadas/crm-dev.png",
  },
  {
    titulo: "Administrador de Empleados",
    descripcion:"Proyecto realizado con Vue3 usando Composition API, asi como el uso del localStorage para hacer persistente los datos. Se empleo el framework TailwindCss para los estilos y tambien se uso Vite",
    tecnologias: ["vuejs", "tailwind-css"],
    tipo: "Frontend",
    fecha: "26 Julio 2024",
    enlace: "https://devomar-administrador-empleados-vue.vercel.app/",
    repositorio: "https://github.com/Dev-socar/administrador-empleados-vue",
    imagen: "src/portadas/adminEmpleados_vue.png",
  },
  {
    titulo: "StoreDev",
    descripcion:"Proyecto realizado con Vue3 usando Composition API, asi como el uso del localStorage para hacer persistente la funcionalidad del carro de compras. Se empleo el framework TailwindCss para los estilos y tambien se uso Vite",
    tecnologias: ["vuejs", "tailwind-css"],
    tipo: "Frontend",
    fecha: "18 Julio 2024",
    enlace: "https://store-dev-sigma.vercel.app/",
    repositorio: "https://github.com/Dev-socar/storeDev",
    imagen: "src/portadas/storedev.png",
  },
  {
    titulo: "CarShop",
    descripcion:
      "Este proyecto consiste en poder agregar a una seccion de Favoritos, diferentes autos y poder ver la descripcion de cada uno de ellos. Asi mismo, para la obtenecion de los datos se emplea la api de Fetch y asi mismo se realiza la peticion a una API externa. Para que los datos sean persistentes se almacenan en el localstorage.",
    tecnologias: ["html5", "javascript", "tailwind-css", "netlify"],
    tipo: "Frontend",
    fecha: "5 Junio 2024",
    enlace: "https://devomar-carshop.netlify.app/",
    repositorio: "https://github.com/Dev-socar/CarShop/tree/dev",
    imagen: "src/portadas/carshop.png",
  },
  {
    titulo: "GuitarLa",
    descripcion:
      "Este proyecto es totalmente responsive, así mismo cuenta con alguna animación y también fué implementado usando SASS con CSS Grid y Flexbox para la distribución de los elementos.",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "25 Abril 2024",
    enlace: "https://devomar-guitarla.netlify.app",
    repositorio: "https://github.com/Dev-socar/GuitarLA",
    imagen: "src/portadas/guitarla.png",
  },
  {
    titulo: "Escuela de Cocina",
    descripcion:
      "Este proyecto es totalmente responsive, así mismo cuenta con alguna animación y también fué implementado usando SASS con CSS Grid y Flexbox para la distribución de los elementos y cuenta con un diseño moderno.",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "24 Abril 2024",
    enlace: "https://devomar-escuelacomida.netlify.app/",
    repositorio: "https://github.com/Dev-socar/EscuelaCocina",
    imagen: "src/portadas/escuelacomida.png",
  },
  {
    titulo: "Carolina Spa",
    descripcion:
      "Este proyecto es totalmente responsive, así mismo cuenta con alguna animación y también fué implementado usando SASS con CSS Grid y Flexbox para la distribución de los elementos. De igual manera se agregó la librería Swiper.js para realizar un slider de imagenes y también un efecto de parallax.",
    tecnologias: ["html5", "sass", "css3", "javascript", "netlify"],
    tipo: "Frontend",
    fecha: "18 Abril 2024",
    enlace: "https://devomar-carolinaspa.netlify.app",
    repositorio: "https://github.com/Dev-socar/SpaWebsite",
    imagen: "src/portadas/carolinaspa.png",
  },
  {
    titulo: "Real State",
    descripcion:
      "Este proyecto es totalmente responsive y también fué implementado usando SASS con CSS Grid y Flexbox para la distribución de los elementos. Se uso Mixins en SASS para agilizar algunos estilos y ser más productivo.",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "13 Abril 2024",
    enlace: "https://devomar-realstate.netlify.app",
    repositorio: "https://github.com/Dev-socar/RealState",
    imagen: "src/portadas/realstate.png",
  },
  {
    titulo: "App Delivery",
    descripcion:
      "Este proyecto es totalmente responsive y también fué implementado usando SASS con CSS Grid y Flexbox para la distribución de los elementos. Se uso Mixins en SASS para agilizar algunos estilos y ser más productivo.",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "15 Marzo 2024",
    enlace: "https://devomar-appcomida.netlify.app/",
    repositorio: "https://github.com/Dev-socar/AppComida",
    imagen: "src/portadas/appcomida.png",
  },
  {
    titulo: "NotasDev",
    descripcion:
      "Este proyecto está realizado con tailwindcss, html5 y vanilla js, el diseño es totalmente responsivo. En sí mismo, este proyecto sería como una aplicación en la que el usuario puede crear notas y estas permanecen persistentes en la página. Todo esto fue posible utilizando LocalStorage y también la validación de los formularios. Usuario:Tokito Contraseña:Tokito123",
    tecnologias: ["tailwind-css", "html5", "javascript", "netlify"],
    tipo: "Frontend",
    fecha: "12 Marzo 2024",
    enlace: "https://devomar-devnotas.netlify.app/",
    repositorio: "https://github.com/Dev-socar/DevNotas",
    imagen: "src/portadas/notasdev.png",
  },
  {
    titulo: "La Cafeteria",
    descripcion: "",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "02 Marzo 2024",
    enlace: "https://devomar-cafeteria.netlify.app/",
    repositorio: "https://github.com/Dev-socar/LaCafeter-a",
    imagen: "src/portadas/lacafeteria.png",
  },
  {
    titulo: "Nucleus - eWallet",
    descripcion:
      "Este proyecto es totalmente responsive, lo desarrollé usando la metodología BEM para que mi código CSS sea más reutilizable y mejor estructurado. También utilicé CSS Grid y Flexbox para el posicionamiento de los elementos.",
    tecnologias: ["css3", "html5", "netlify"],
    tipo: "Frontend",
    fecha: "15 Febrero 2024",
    enlace: "https://devomar-nucleus.netlify.app/",
    repositorio: "https://github.com/Dev-socar/Nucleus",
    imagen: "src/portadas/nucleus.png",
  },
  {
    titulo: "DevWebCamp",
    descripcion:
      "DevWebCamp es una aplicación web completa. Tiene inscripciones para conferencias o talleres, el usuario debe tener una cuenta y una vez creada debe seleccionar un paquete y en este punto se implementó una pasarela de pago a través de Paypal. Dentro de la aplicación, se utilizan solicitudes API. Se utilizó la biblioteca de folletos para el mapa y Chart.js para crear gráficos. Cuenta con un panel administrativo donde el administrador puede ver los ingresos, los últimos registros, programar las charlas, así como registrar a los ponentes. Se utilizó la arquitectura MVC.",
    tecnologias: [
      "css3",
      "html5",
      "sass",
      "php",
      "javascript",
      "github",
      "paypal",
    ],
    tipo: "FullStack",
    fecha: "17 Enero 2024",
    enlace: "https://devwebcamp-omarsolis.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/DevWebCamp",
    imagen: "src/portadas/devwebcamp.png",
  },
  {
    titulo: "UpTask",
    descripcion:
      "UpTask es una aplicación del tipo Lista de tareas pendientes, pero le permite crear proyectos y definir tareas en esos proyectos, así como filtrar tareas completas e incompletas. Las solicitudes al servidor se realizan a través de APIs. Asimismo, la aplicación está diseñada con la arquitectura MVC usando PHP del lado del servidor y hace uso de sesiones. Finalmente, se implementó el modo oscuro o el modo claro dependiendo del modo que tenga el usuario en su dispositivo.",
    tecnologias: ["css3", "html5", "javascript", "php"],
    tipo: "FullStack",
    fecha: "18 Septiembre 2023",
    enlace: "https://uptaskapp.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/UpTask",
    imagen: "src/portadas/uptask.png",
  },
  {
    titulo: "TechPro",
    descripcion:
      "En este proyecto implementé y profundicé en CSS Grid y Flexbox. Techpro es una página de inicio que se supone promociona los auriculares, con CSS Grid se diseñaron diseños más atractivos y modernos.",
    tecnologias: ["css3", "html5", "netlify"],
    tipo: "Frontend",
    fecha: "03 Agosto 2023",
    enlace: "https://tech-prodev.netlify.app/",
    repositorio: "https://github.com/Dev-socar/TechPro",
    imagen: "src/portadas/techpro.png",
  },
  {
    titulo: "VetBlue",
    descripcion:
      "VetBlue es una aplicación web que permite a la empresa administrar y gestionar citas. El rol de administrador puede CRUDar tus servicios, así como filtrar tus citas programadas por día y, una vez atendidas, poder eliminarlas. Por otro lado, los usuarios deben tener una cuenta en la aplicación, de lo contrario deberán crear una y verificar la cuenta que crearon vía correo electrónico. Se utilizó el patrón de arquitectura MVC.",
    tecnologias: ["css3", "html5", "javascript", "php"],
    tipo: "FullStack",
    fecha: "23 Mayo 2023",
    enlace: "https://vetblue.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/VET_MVC",
    imagen: "src/portadas/vetblue.png",
  },
  {
    titulo: "Empresa Inmobiliaria Corpesa",
    descripcion:
      "Este sitio web cuenta con un panel administrativo, en ese panel el administrador puede realizar un CRUD de las propiedades. Asimismo, implementé la API de Google Maps para que al crear una propiedad se pueda seleccionar mediante un pin de ubicación.",
    tecnologias: ["css3", "html5", "php", "javascript"],
    tipo: "FullStack",
    fecha: "12 Diciembre 2022",
    enlace: "https://corpesainmobiliaria.com/",
    repositorio: "",
    imagen: "src/portadas/corpesa.png",
  },
];
