const proyectos = [
  {
    titulo: "GuitarLa",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "25 Abril 2024",
    enlace: "https://devomar-guitarla.netlify.app",
    repositorio: "https://github.com/Dev-socar/GuitarLA",
    imagen: "src/portadas/guitarla.png",
  },
  {
    titulo: "Escuela de Cocina",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "24 Abril 2024",
    enlace: "https://devomar-escuelacomida.netlify.app/",
    repositorio: "https://github.com/Dev-socar/EscuelaCocina",
    imagen: "src/portadas/escuelacomida.png",
  },
  {
    titulo: "Carolina Spa",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["html5", "sass", "css3", "javascript", "netlify"],
    tipo: "Frontend",
    fecha: "18 Abril 2024",
    enlace: "https://devomar-carolinaspa.netlify.app",
    repositorio: "https://github.com/Dev-socar/SpaWebsite",
    imagen: "src/portadas/carolinaspa.png",
  },
  {
    titulo: "Real State",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "13 Abril 2024",
    enlace: "https://devomar-realstate.netlify.app",
    repositorio: "https://github.com/Dev-socar/RealState",
    imagen: "src/portadas/realstate.png",
  },
  {
    titulo: "App Delivery",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "15 Marzo 2024",
    enlace: "https://devomar-appcomida.netlify.app/",
    repositorio: "https://github.com/Dev-socar/AppComida",
    imagen: "src/portadas/appcomida.png",
  },
  {
    titulo: "NotasDev",
    descripcion:
      "This project is made with tailwindcss, html5 and vanilla js, the design is fully responsive. In itself, this project would be like an application in which the user can create notes and they remain persistent on the page. All this was possible using LocalStorage and also validation of the forms",
    tecnologias: ["tailwind-css", "html5", "javascript", "netlify"],
    tipo: "Frontend",
    fecha: "12 Marzo 2024",
    enlace: "https://devomar-devnotas.netlify.app/",
    repositorio: "https://github.com/Dev-socar/DevNotas",
    imagen: "src/portadas/notasdev.png",
  },
  {
    titulo: "La Cafeteria",
    descripcion: "",
    tecnologias: ["html5", "sass", "css3", "netlify"],
    tipo: "Frontend",
    fecha: "02 Marzo 2024",
    enlace: "https://devomar-cafeteria.netlify.app/",
    repositorio: "https://github.com/Dev-socar/GuitarLA",
    imagen: "src/portadas/lacafeteria.png",
  },
  {
    titulo: "Nucleus - eWallet",
    descripcion: "",
    tecnologias: ["css3", "html5", "netlify"],
    tipo: "Frontend",
    fecha: "15 Febrero 2024",
    enlace: "https://devomar-nucleus.netlify.app/",
    repositorio: "https://github.com/Dev-socar/LaCafeter-a",
    imagen: "src/portadas/nucleus.png",
  },
  {
    titulo: "DevWebCamp",
    descripcion: "",
    tecnologias: [
      "css3",
      "html5",
      "sass",
      "php",
      "javascript",
      "github",
      "paypal",
    ],
    tipo: "FullStack",
    fecha: "17 Enero 2024",
    enlace: "https://devwebcamp-omarsolis.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/DevWebCamp",
    imagen: "src/portadas/devwebcamp.png",
  },
  {
    titulo: "UpTask",
    descripcion: "",
    tecnologias: ["css3", "html5", "javascript", "php"],
    tipo: "FullStack",
    fecha: "18 Septiembre 2023",
    enlace: "https://uptaskapp.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/UpTask",
    imagen: "src/portadas/uptask.png",
  },
  {
    titulo: "VetBlue",
    descripcion: "",
    tecnologias: ["css3", "html5", "javascript", "php"],
    tipo: "FullStack",
    fecha: "23 Mayo 2023",
    enlace: "https://vetblue.000webhostapp.com/",
    repositorio: "https://github.com/Dev-socar/VET_MVC",
    imagen: "src/portadas/vetblue.png",
  },
  {
    titulo: "TechPro",
    descripcion: "",
    tecnologias: ["css3", "html5", "netlify"],
    tipo: "Frontend",
    fecha: "03 Agosto 2023",
    enlace: "https://tech-prodev.netlify.app/",
    repositorio: "https://github.com/Dev-socar/TechPro",
    imagen: "src/portadas/techpro.png",
  },
  {
    titulo: "Empresa Inmobiliaria Corpesa",
    descripcion: "",
    tecnologias: ["css3", "html5", "php", "javascript"],
    tipo: "FullStack",
    fecha: "12 Diciembre 2022",
    enlace: "https://corpesainmobiliaria.com/",
    repositorio: "",
    imagen: "src/portadas/corpesa.png",
  },
];
